# Generated by Django 3.1.5 on 2021-02-03 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.SlugField(verbose_name='Ссылка')),
                ('hash', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Коментарии',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=25, verbose_name='Имя сообщества')),
                ('adress', models.SlugField(verbose_name='адресс сервера')),
            ],
            options={
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.SlugField(verbose_name='Ссылка')),
                ('hash', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centralserver.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centralserver.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centralserver.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centralserver.user')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centralserver.user', verbose_name='Владелец'),
        ),
        migrations.CreateModel(
            name='AnswersOfInterviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_id', models.IntegerField(verbose_name='id опроса ')),
                ('answer_number', models.IntegerField(verbose_name='Номер ответа')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centralserver.user')),
            ],
            options={
                'verbose_name_plural': 'Ответы на опросы',
            },
        ),
    ]
